[package]
name = "nvalloc"
version = "0.1.0"
edition = "2018"

[profile.release]
lto = "thin"
opt-level = 3

[dependencies]
log = "0.4"
libc = "0.2"
bitfield-struct = "0.1.1"
num_cpus = "1.13"
buddy_system_allocator = "0.8.0"
env_logger = { version = "0.9", default-features = false, optional = true }

[dev-dependencies]
env_logger = { version = "0.9", default-features = false }

[features]
wait = []
log_debug = ["log/max_level_debug"]
log_info = ["log/max_level_info"]
log_warn = ["log/max_level_warn"]
log_error = ["log/max_level_error"]
thread = []
logger = ["env_logger"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "10.2"

[[example]]
name = "bench"
required-features = ["logger", "thread"]
