[package]
name = "nvalloc"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
libc = { version = "0.2", optional = true }
bitfield-struct = "0.1.7"
env_logger = { version = "0.9", default-features = false, optional = true }
spin = { version = "0.9.3", default-features = false, features = ["use_ticket_mutex", "barrier"] }
log = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = ["log/std", "libc", "env_logger"]
log_debug = ["log/max_level_debug"]
log_info = ["log/max_level_info"]
log_warn = ["log/max_level_warn"]
log_error = ["log/max_level_error"]
stop = ["std"]
