[alias]
perf = ["run", "-pnvalloc-bench", "-r", "--bin"]
perf-build = ["build", "-pnvalloc-bench", "-r", "--bin"]
module = ["build", "-pnvalloc-module", "-r", "--target=module/x86_64-linux-gnu.json", "-Zbuild-std=core,alloc,compiler_builtins"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-none]
rustflags = ["-C", "target-cpu=native"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
