[alias]
perf = ["run", "--features=logger", "--features=thread", "--features=log_warn", "--release", "--example"]
perf-build = ["build", "--features=logger", "--features=thread", "--features=log_warn", "--release", "--example"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
